import DS from 'ember-data';

export default DS.Model.extend({
  acquisitionSaleOfBusinessNet: DS.attr('number'),
  adjustmentForEquityEarnings: DS.attr('number'),
  adjustmentForMinorityInterest: DS.attr('number'),
  adjustmentForSpecialCharges: DS.attr('number'),
  capitalExpenditures: DS.attr('number'),
  cashFromDiscontinuedOperations: DS.attr('number'),
  cashFromFinancingActivities: DS.attr('number'),
  cashFromInvestingActivities: DS.attr('number'),
  cashFromOperatingActivities: DS.attr('number'),
  cashFromDepreciationAmortization: DS.attr('number'),
  changeInAccountsPayableAccruedExpenses: DS.attr('number'),
  changeInAccountsReceivable: DS.attr('number'),
  changeInCurrentAssets: DS.attr('number'),
  changeInCurrentLiabilities: DS.attr('number'),
  changeInDebtNet: DS.attr('number'),
  changeInDeferredRevenue: DS.attr('number'),
  changeInEquityNet: DS.attr('number'),
  changeInIncomeTaxesPayable: DS.attr('number'),
  changeInInventories: DS.attr('number'),
  changeInOperatingAssetsLiabilities: DS.attr('number'),
  changeInOtherAssets: DS.attr('number'),
  changeInOtherCurrentAssets: DS.attr('number'),
  changeInOtherCurrentLiabilities: DS.attr('number'),
  changeInOtherLiabilities: DS.attr('number'),
  changeInPrepaidExpenses: DS.attr('number'),
  deferredIncomeTaxes: DS.attr('number'),
  dividendsPaid: DS.attr('number'),
  effectOfExChangeRateOnCash: DS.attr('number'),
  employeeCompensation: DS.attr('number'),
  investmentChangesNet: DS.attr('number'),
  netChangeInCash: DS.attr('number'),
  otherAdjustments: DS.attr('number'),
  otherAssetLiabilityChangesNet: DS.attr('number'),
  otherFinancingActivitiesNet: DS.attr('number'),
  otherInvestingActivities: DS.attr('number'),
  realizedGainsLosses: DS.attr('number'),
  saleOfPropertyPlantEquipment: DS.attr('number'),
  stockOptionTaxBenefits: DS.attr('number'),
  totalAdjustments: DS.attr('number')
});
